---
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--rcfile=back/.pylintrc",
            "-rn",
            "-sn"
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: 
          [
            --no-strict-optional, 
            --ignore-missing-imports
          ]
