from bluff.game import get_sequence_hierarchy


def test_get_sequences_hierarchy():
    hierarchy = get_sequence_hierarchy()
    assert hierarchy == [
        '[High card] 9',
        '[High card] 10',
        '[High card] jack',
        '[High card] queen',
        '[High card] king',
        '[High card] ace',
        '[One pair] 9',
        '[One pair] 10',
        '[One pair] jack',
        '[One pair] queen',
        '[One pair] king',
        '[One pair] ace',
        '[Two pair] 10;9',
        '[Two pair] jack;9',
        '[Two pair] jack;10',
        '[Two pair] queen;9',
        '[Two pair] queen;10',
        '[Two pair] queen;jack',
        '[Two pair] king;9',
        '[Two pair] king;10',
        '[Two pair] king;jack',
        '[Two pair] king;queen',
        '[Two pair] ace;9',
        '[Two pair] ace;10',
        '[Two pair] ace;jack',
        '[Two pair] ace;queen',
        '[Two pair] ace;king',
        '[Small straight]',
        '[Big straight]',
        '[Three of a kind] 9',
        '[Three of a kind] 10',
        '[Three of a kind] jack',
        '[Three of a kind] queen',
        '[Three of a kind] king',
        '[Three of a kind] ace',
        '[Full 3x2] 9;10',
        '[Full 3x2] 9;jack',
        '[Full 3x2] 9;queen',
        '[Full 3x2] 9;king',
        '[Full 3x2] 9;ace',
        '[Full 3x2] 10;9',
        '[Full 3x2] 10;jack',
        '[Full 3x2] 10;queen',
        '[Full 3x2] 10;king',
        '[Full 3x2] 10;ace',
        '[Full 3x2] jack;9',
        '[Full 3x2] jack;10',
        '[Full 3x2] jack;queen',
        '[Full 3x2] jack;king',
        '[Full 3x2] jack;ace',
        '[Full 3x2] queen;9',
        '[Full 3x2] queen;10',
        '[Full 3x2] queen;jack',
        '[Full 3x2] queen;king',
        '[Full 3x2] queen;ace',
        '[Full 3x2] king;9',
        '[Full 3x2] king;10',
        '[Full 3x2] king;jack',
        '[Full 3x2] king;queen',
        '[Full 3x2] king;ace',
        '[Full 3x2] ace;9',
        '[Full 3x2] ace;10',
        '[Full 3x2] ace;jack',
        '[Full 3x2] ace;queen',
        '[Full 3x2] ace;king',
        '[Color] spades',
        '[Color] clubs',
        '[Color] diamonds',
        '[Color] hearts',
        '[Four of a kind] 9',
        '[Four of a kind] 10',
        '[Four of a kind] jack',
        '[Four of a kind] queen',
        '[Four of a kind] king',
        '[Four of a kind] ace',
        '[Small poker] spades',
        '[Small poker] clubs',
        '[Small poker] diamonds',
        '[Small poker] hearts',
        '[Big poker] spades',
        '[Big poker] clubs',
        '[Big poker] diamonds',
        '[Big poker] hearts'
    ]
